### ISSUE TITLE
Sorry I don't know where to go to ask you

### ISSUE THREAD

**Issue by eramosr16** [Kacper-Pietkun/Stock-Trading-With-Neat-Algorithm#1]
Did you implemented the Neat or you just reference and existing implementation?

**Comment by Kacper-Pietkun** [comment]
Hi, I used an existing implementation

**Comment by polonezu1985** [comment]
i whant to test on live enviroment ,can you give us one implemetation ex. please?

**Comment by Kacper-Pietkun** [comment]
Hi @polonezu1985, sorry, but I am not planning to implement live environment tests in the nearest future.
